### ISSUE TITLE
Incompréhension à l’initiation du client 

### ISSUE THREAD

**Issue by WebMatPro** [FivemTools/ft_gamemode#5]
Bonjour,

merci pour ton gamemode, je commence sur les FXserver de FiveM et je souhaitais quelque chose de simple pour débuter.

Je suppose que quand le client charge les données mais n'arrive pas jusqu'à l'affichage In game, c'est qu'il y a une erreur au niveau serveur.

Déjà voici les étapes qui ont été accomplis 👍 
1 - FXserver vanilla opérationnel
2 - Mise en place de MYSQL sync, avec un petit script pour vérifier que j'ai une bonne co 
3 - Mise en place de ton gamemode, rajout dans le cfg "start ft_gamemode"

et là je bloque à la fin du chargement du client, plus rien. Note encore une fois que tout est absolument d'origine.

J'ai rajouté mes logs en dessous pour que tu comprennes plus rapidement le problème (au moment du run server)

Merci d'avance pour ton aide.

ps: je suis webmaster, et je vais développer un système de connexion propre, via inscription hors fivem puis la connexion sur fivem, je serais ravis de pouvoir te partager cela quand ça sera créé.

> `Microsoft Windows [version 10.0.15063]
> (c) 2017 Microsoft Corporation. Tous droits réservés.
> 
> C:\WINDOWS\system32>cd c:\FXServerGTA5
> 
> c:\FXServerGTA5>run.cmd +exec server.cfg
> Initializing Mono
> Initializing Mono completed
> Hello!
> Stacktrace:
> 
> 
> 
> =================================================================
> Got a SIGSEGV while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries
> used by your application.
> =================================================================
> 
> 
> Failed to get instance for guid a7242855-0350-4cb5-a0fe-61021e7eafaa and iid 567634c6-3bdd-4d0e-af39-7472aed479b7: System.InvalidOperationException: Sequence contains no matching element
>   at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) [0x00011] in <48501e5f32e8491e924f8b8beae3e4f6>:0
>   at CitizenFX.Core.RuntimeManager.CreateObjectInstance (System.Guid guid, System.Guid iid) [0x00014] in C:\gl\builds\4ff63adb\0\cfx\fivem\code\client\clrcore\RuntimeManager.cs:39
> Found new resource fivem in c:/FXServerGTA5/resources//fivem
> Found new resource fivem-awesome1501 in c:/FXServerGTA5/resources//fivem-awesome1501
> Found new resource fivem-map-hipster in c:/FXServerGTA5/resources//fivem-map-hipster
> Found new resource fivem-map-skater in c:/FXServerGTA5/resources//fivem-map-skater
> Found new resource mysql-async in c:/FXServerGTA5/resources//mysql-async
> Found new resource test in c:/FXServerGTA5/resources//test
> Found new resource ft_gamemode in c:/FXServerGTA5/resources//[gamemodes]/ft_gamemode
> Found new resource race in c:/FXServerGTA5/resources//[gamemodes]/race
> Found new resource race-test in c:/FXServerGTA5/resources//[gamemodes]/race-test
> Found new resource channelfeed in c:/FXServerGTA5/resources//[gameplay]/channelfeed
> Found new resource irc in c:/FXServerGTA5/resources//[gameplay]/irc
> Found new resource obituary in c:/FXServerGTA5/resources//[gameplay]/obituary
> Found new resource obituary-deaths in c:/FXServerGTA5/resources//[gameplay]/obituary-deaths
> Found new resource mapmanager in c:/FXServerGTA5/resources//[managers]/mapmanager
> Found new resource baseevents in c:/FXServerGTA5/resources//[system]/baseevents
> Found new resource chat in c:/FXServerGTA5/resources//[system]/chat
> Found new resource hardcap in c:/FXServerGTA5/resources//[system]/hardcap
> Found new resource rconlog in c:/FXServerGTA5/resources//[system]/rconlog
> Found new resource scoreboard in c:/FXServerGTA5/resources//[system]/scoreboard
> Found new resource sessionmanager in c:/FXServerGTA5/resources//[system]/sessionmanager
> Found new resource spawnmanager in c:/FXServerGTA5/resources//[system]/spawnmanager
> Found new resource betaguns in c:/FXServerGTA5/resources//[test]/betaguns
> Found new resource gameInit in c:/FXServerGTA5/resources//[test]/gameInit
> Found new resource keks in c:/FXServerGTA5/resources//[test]/keks
> Started resource sessionmanager
> Started resource mapmanager
> Started resource chat
> Started resource spawnmanager
> Started resource fivem
> Started gametype Freeroam
> Started resource hardcap
> Started resource rconlog
> Started resource scoreboard
> Loaded MySqlAsync.net, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_148303715
> Loaded MySqlConnector, Version=0.23.0.0, Culture=neutral, PublicKeyToken=null into ScriptDomain_148303715
> Instantiated instance of script MySqlAsync.MySqlAsync.
> Started resource mysql-async
> Changing gametype from fivem to ft_gamemode
> Stopping resource fivem
> Started resource ft_gamemode
> Started gametype FiveMTools v0.14.1
**> Error running system event handling function for resource mapmanager: citizen:/scripting/lua/scheduler.lua:39: Failed to execute thread: mapmanager_server.lua:222: attempt to concatenate a nil value
> stack traceback:
>         mapmanager_server.lua:222: in upvalue 'handler'
>         citizen:/scripting/lua/scheduler.lua:124: in function <citizen:/scripting/lua/scheduler.lua:123>
> stack traceback:
>         [C]: in function 'error'
>         citizen:/scripting/lua/scheduler.lua:39: in field 'CreateThreadNow'
>         citizen:/scripting/lua/scheduler.lua:123: in function <citizen:/scripting/lua/scheduler.lua:92>
> No such command map.**
> cfx> Resolved live-internal.fivem.net:30110 to 151.80.44.223:30110`

**Comment by samuelds** [comment]
A tu fait comme ici : https://fivemtools.readme.io/docs/gamemode-install

Change gametype to map ressource :

```
__ressource.lua
 resource_type 'map' { gameTypes = { ft_gamemode = true } }
```

J'ai pas encore eu le temps de changer le readme.

A tu les ressources pour fxserveur : https://github.com/citizenfx/cfx-server-data.git ?

**Comment by WebMatPro** [comment]
Salut,

non et merci c'est impec, je n'ai plus d'erreur et la map se charge bien.

Je commence à comprendre le principe (pas évident vu le peu de doc sur fivem)

Au final, je load ma map d'origine (juste un spawn et gamemode obligatoire) et je start : 
start mapmanager
start chat
start spawnmanager
start hardcap
start rconlog
start scoreboard

start mysql-async
start ft_gamemode


Donc si je comprends bien ton gamemode, pour le moment, il ne rajoute absolument rien ingame (c'est niquel) et pour le moment, il enregistre le steamid en mysql et met en place des configurations server.

Aurais tu besoins d'aide pour la documentation ? 

En tous cas merci beaucoup, maintenant j'ai une base propre, je vais commencer le développement pour mon système de connexion via compte en mysql.

mon discord si tu veux en discuter : Mat Pain#8741

Merci encore,
Mat.
